### ISSUE TITLE
Create a test case for Pad op

### ISSUE THREAD

**Issue by houseroad** [ezyang/onnx-pytorch#15]
Test the Pad op.

**Comment by bddppq** [comment]
For backend, there are tests for Pad op at https://github.com/onnx/onnx/blob/master/onnx/backend/test.py#L39

**Comment by houseroad** [comment]
Cool, it's also good to have a e2e test case here. :-)

**Comment by houseroad** [comment]
Probably I can extend the existing tests to e2e.

**Comment by houseroad** [comment]
It's done #18
