### ISSUE TITLE
onnx.helper missing in test_models

### ISSUE THREAD

**Issue by jamesr66a** [ezyang/onnx-pytorch#32]
https://github.com/ezyang/onnx-pytorch/blob/9b522e7901ac3fd17c1f256527e8bd42769255a5/test/test_models.py#L50

When I run test_models.py locally, I get a failure because Python cannot find onnx.helper. However, if I add `import onnx.helper` to the file, it runs fine. It's strange because this seems to work on contbuild, can anyone shed light? Is this an issue in my local configuration?

**Comment by ezyang** [comment]
If you update to onnx-pytorch HEAD this should be fixed (make sure you update submodules.)

The fix is also in onnx master, see https://github.com/onnx/onnx/pull/161
